a=int(input("No of coins suresh initially have:"));
b=int(input("No of coins sundar initially have:"));
c=int(input("No of coins raja initially have:"));
d=int(input("No of coins suresh gave to sundar:"));
if a>b:
   print("First:Suresh is winner");
   b=b+c;
else:
   print("First:Sundar is winner");
   a=a+c;
if a>b:
   print("Second:Suresh is winner");
   b=b+d;
else:
   print("Second:Sundar vis winner");
   a=a+b;
if a>b:
   print("Final:Suresh is winner");
else:
   print("Final:Sundar is winner");
